/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AdminAuditLogs {
  action: string;
  admin_id: string;
  after_data: Json | null;
  before_data: Json | null;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  id: Generated<Int8>;
  ip_address: string | null;
}

export interface AdminPasswordResetTokens {
  admin_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
}

export interface AdminUsers {
  created_at: Generated<Timestamp>;
  display_name: string;
  email: string;
  failed_login_count: Generated<number>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  must_change_password: Generated<boolean>;
  password_hash: string;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AppSettings {
  description: string | null;
  setting_key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Json | null;
}

export interface AuthSessions {
  client: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  revoked_at: Timestamp | null;
  subject_id: string;
  subject_type: string;
  token_hash: string;
  user_agent: string | null;
}

export interface CartItems {
  cart_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  quantity: number;
  updated_at: Generated<Timestamp>;
  variant_id: string;
}

export interface Carts {
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  guest_token: string | null;
  id: Generated<string>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ClothingTypes {
  id: Generated<string>;
  is_active: Generated<boolean>;
  search_keywords: Generated<string>;
  slug: string;
  sort_order: Generated<number>;
}

export interface ClothingTypeTranslations {
  clothing_type_id: string;
  language_code: string;
  name: string;
}

export interface ContentBlocks {
  block_key: string;
  id: Generated<string>;
  is_published: Generated<boolean>;
  media_asset_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface ContentBlockTranslations {
  body: string | null;
  content_block_id: string;
  cta_label: string | null;
  language_code: string;
  title: string | null;
}

export interface CustomerAddresses {
  address_line1: string;
  address_line2: string | null;
  city: string;
  created_at: Generated<Timestamp>;
  customer_id: string;
  delivery_zone_id: string;
  id: Generated<string>;
  is_default: Generated<boolean>;
  label: string | null;
  landmark: string | null;
  phone: string;
  recipient_name: string;
  state: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Customers {
  anonymized_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  failed_login_count: Generated<number>;
  full_name: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  password_hash: string;
  phone: string | null;
  preferred_language: Generated<string>;
  status: Generated<string>;
  terms_accepted_at: Timestamp | null;
  terms_version: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DeliveryZones {
  code: string;
  created_at: Generated<Timestamp>;
  est_days_max: number | null;
  est_days_min: number | null;
  fee_minor: Int8 | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_sample_data: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface EmailOutbox {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  language_code: string;
  last_error: string | null;
  next_attempt_at: Generated<Timestamp>;
  order_id: string | null;
  payload: Json;
  recipient: string;
  sent_at: Timestamp | null;
  status: Generated<string>;
  template: string;
}

export interface EmailVerificationTokens {
  created_at: Generated<Timestamp>;
  customer_id: string;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  id: Generated<string>;
  idem_key: string;
  request_hash: string;
  response_body: Json | null;
  response_status: number | null;
  scope: string;
  subject_id: string | null;
}

export interface Languages {
  code: string;
  is_active: Generated<boolean>;
  is_default: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
}

export interface MeasurementTypes {
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  sort_order: Generated<number>;
  unit: Generated<string>;
}

export interface MeasurementTypeTranslations {
  help_text: string | null;
  label: string;
  language_code: string;
  measurement_type_id: string;
}

export interface MediaAssets {
  created_at: Generated<Timestamp>;
  duration_ms: number | null;
  height: number | null;
  id: Generated<string>;
  is_temporary: Generated<boolean>;
  kind: string;
  mime_type: string;
  original_key: string;
  poster_asset_id: string | null;
  processing_status: Generated<string>;
  size_bytes: Int8;
  updated_at: Generated<Timestamp>;
  uploaded_by: string | null;
  width: number | null;
}

export interface MediaRenditions {
  asset_id: string;
  bitrate_kbps: number | null;
  format: string;
  height: number | null;
  id: Generated<string>;
  label: string;
  size_bytes: Int8 | null;
  storage_key: string;
  width: number | null;
}

export interface OrderItems {
  clothing_type_name: string;
  id: Generated<string>;
  line_total_minor: Int8;
  order_id: string;
  product_id: string;
  product_name: string;
  quantity: number;
  size_label: string;
  sku: string;
  unit_price_minor: Int8;
  variant_id: string;
}

export interface Orders {
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  carrier: string | null;
  contact_email: string;
  contact_phone: string;
  created_at: Generated<Timestamp>;
  currency: string;
  customer_id: string;
  delivered_at: Timestamp | null;
  delivery_fee_minor: Int8;
  delivery_zone_id: string | null;
  delivery_zone_name: string;
  id: Generated<string>;
  idempotency_key: string;
  internal_note: string | null;
  language_code: string;
  order_number: Generated<string>;
  order_status: Generated<string>;
  paid_at: Timestamp | null;
  payment_status: Generated<string>;
  placed_at: Generated<Timestamp>;
  recipient_name: string;
  reservation_expires_at: Timestamp | null;
  ship_address_line1: string;
  ship_address_line2: string | null;
  ship_city: string;
  ship_landmark: string | null;
  ship_state: string | null;
  source_client: string;
  subtotal_minor: Int8;
  total_minor: Int8;
  tracking_reference: string | null;
  updated_at: Generated<Timestamp>;
}

export interface OrderStatuses {
  code: string;
  is_admin_selectable: Generated<boolean>;
  is_terminal: Generated<boolean>;
  label: string;
  sort_order: number;
}

export interface OrderStatusHistory {
  changed_by_admin: string | null;
  created_at: Generated<Timestamp>;
  from_status: string | null;
  id: Generated<Int8>;
  note: string | null;
  order_id: string;
  to_status: string;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  customer_id: string;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
}

export interface Payments {
  amount_minor: Int8;
  channel: string | null;
  created_at: Generated<Timestamp>;
  currency: string;
  gateway_response: string | null;
  id: Generated<string>;
  order_id: string;
  paid_at: Timestamp | null;
  provider: Generated<string>;
  provider_transaction_id: string | null;
  raw_verify_payload: Json | null;
  reference: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  verified_at: Timestamp | null;
}

export interface PaymentWebhookEvents {
  event_type: string;
  id: Generated<string>;
  payload: Json;
  processed_at: Timestamp | null;
  processing_error: string | null;
  provider: Generated<string>;
  provider_event_key: string;
  received_at: Generated<Timestamp>;
  reference: string | null;
  signature_valid: boolean;
}

export interface ProductImages {
  id: Generated<string>;
  media_asset_id: string;
  product_id: string;
  sort_order: Generated<number>;
}

export interface Products {
  clothing_type_id: string;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  display_order: Generated<number>;
  id: Generated<string>;
  name: string;
  price_minor: Int8;
  search_keywords: Generated<string>;
  size_chart_id: string | null;
  slug: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  video_asset_id: string | null;
}

export interface ProductTranslations {
  description: string;
  language_code: string;
  product_id: string;
}

export interface ProductVariants {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  low_stock_threshold: Generated<number>;
  product_id: string;
  row_version: Generated<number>;
  size_id: string;
  sku: string;
  stock_on_hand: Generated<number>;
  stock_reserved: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface QrPages {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_published: Generated<boolean>;
  media_asset_id: string | null;
  slot_number: number;
  slug: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface QrPageTranslations {
  body: string;
  language_code: string;
  qr_page_id: string;
  title: string;
}

export interface SizeChartRanges {
  id: Generated<string>;
  max_value: Numeric;
  measurement_type_id: string;
  min_value: Numeric;
  size_chart_id: string;
  size_id: string;
}

export interface SizeCharts {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_sample_data: Generated<boolean>;
  name: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Sizes {
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  label: string;
  sort_order: Generated<number>;
}

export interface StockMovements {
  admin_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  movement_type: string;
  note: string | null;
  quantity_delta: number;
  reference_id: string | null;
  reference_type: string | null;
  variant_id: string;
}

export interface StockReservations {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  order_id: string;
  quantity: number;
  status: Generated<string>;
  variant_id: string;
}

export interface UiTranslations {
  id: Generated<string>;
  is_approved: Generated<boolean>;
  language_code: string;
  translation_key: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface DB {
  admin_audit_logs: AdminAuditLogs;
  admin_password_reset_tokens: AdminPasswordResetTokens;
  admin_users: AdminUsers;
  app_settings: AppSettings;
  auth_sessions: AuthSessions;
  cart_items: CartItems;
  carts: Carts;
  clothing_type_translations: ClothingTypeTranslations;
  clothing_types: ClothingTypes;
  content_block_translations: ContentBlockTranslations;
  content_blocks: ContentBlocks;
  customer_addresses: CustomerAddresses;
  customers: Customers;
  delivery_zones: DeliveryZones;
  email_outbox: EmailOutbox;
  email_verification_tokens: EmailVerificationTokens;
  idempotency_keys: IdempotencyKeys;
  languages: Languages;
  measurement_type_translations: MeasurementTypeTranslations;
  measurement_types: MeasurementTypes;
  media_assets: MediaAssets;
  media_renditions: MediaRenditions;
  order_items: OrderItems;
  order_status_history: OrderStatusHistory;
  order_statuses: OrderStatuses;
  orders: Orders;
  password_reset_tokens: PasswordResetTokens;
  payment_webhook_events: PaymentWebhookEvents;
  payments: Payments;
  product_images: ProductImages;
  product_translations: ProductTranslations;
  product_variants: ProductVariants;
  products: Products;
  qr_page_translations: QrPageTranslations;
  qr_pages: QrPages;
  size_chart_ranges: SizeChartRanges;
  size_charts: SizeCharts;
  sizes: Sizes;
  stock_movements: StockMovements;
  stock_reservations: StockReservations;
  ui_translations: UiTranslations;
}
