/**
 * TEMP placeholder. This file is GENERATED by kysely-codegen from the live `ecom` database:
 *
 *   pnpm db:codegen
 *
 * Do not edit by hand. Regenerate after every migration.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type -- TEMP until first codegen run
export interface DB {}
